# Do not touch this value
version: 1

# Modify jump velocity
velocity: 1
velocityY: 1

# Cooldown in seconds - set to 0 to disable
cooldown: 3

# Sound on jump. See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sound:
  enabled: true
  sound: ENTITY_BAT_TAKEOFF
  volume: 1
  pitch: 1

# Messages
message:
  prefix: "<gradient:#FCC45F:#FFF3B1>Jumpy</gradient> <dark_gray>»</dark_gray> "
  noperm: "<red>You don't have permission to use this command.</red>"
  mustbeplayer: "<red>You must be a player to run this command.</red>"
  help: "<gray>Help :<newline>• <gold>/jumpy on</gold> : Enable multiple jumps.<newline>• <gold>/jumpy off</gold> : Disable multiple jumps.</gray>"
  jumpalreadyon: "<gray>Jump already on.</gray>"
  jumpalreadyoff: "<gray>Jump already off.</gray>"
  jumpon: "<green>Jump enabled.</green>"
  jumpoff: "<red>Jump disabled.</red>"
  reload: "<green>Config file reloaded.</green>"